version: "3.8"

services:
  api:
    image: carlossiqueira/prados-turismo:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./public/images:/usr/src/app/public/images
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure
    command: sh -c "npx prisma migrate deploy && npx prisma migrate dev && npm run dev:debug"
    environment:
      KAFKA_BROKER: kafka:9092
      PORT: ${PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@host.docker.internal/pradosturismo?schema=public
      URL_LOGO_PRADOS: https://prados-web.vercel.app/images/prados/logopradosg.png

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/kafka/9092"]
      interval: 10s
      retries: 3
      timeout: 5s
    depends_on:
      zookeeper:
        condition: service_healthy

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "echo", "ruok"]
      interval: 10s
      timeout: 5s
      retries: 3
